name: 'my-actions'
description: 'My description'
inputs:
  cacheing:
    description: 'to cache dependencies or not '
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Cache dependencies
      if: inputs.cacheing == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'  || inputs.cacheing != 'true'
      run: npm ci
      shell: bash
    